const userActionTypes = {
  CURRENT_USER_FETCH_START: "CURRENT_USER_FETCH_START",
  CURRENT_USER_FETCH_SUCCESS: "CURRENT_USER_FETCH_SUCCESS",
  CURRENT_USER_FETCH_FAILURE: "CURRENT_USER_FETCH_FAILURE"
};

export default userActionTypes;
